# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-08 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(max_length=200, verbose_name='\u59d3\u540d')),
                ('phone', models.CharField(max_length=200, verbose_name='\u624b\u673a\u53f7')),
                ('source', models.CharField(choices=[('BAR', 'Bar'), ('KTV', 'KTV')], max_length=20, verbose_name='\u8d2d\u4e70\u6e20\u9053')),
                ('amount', models.CharField(choices=[('three', 'Three bottles'), ('six+', 'Six or more bottles'), ('six', 'Six bottles'), ('twelve+', 'Twelve or more bottles')], max_length=20, verbose_name='\u8d2d\u4e70\u74f6\u6570')),
                ('recipe_num', models.CharField(max_length=200, verbose_name='\u5c0f\u7968\u5355\u53f7')),
            ],
            options={
                'verbose_name': '\u8ba2\u5355',
                'verbose_name_plural': '\u8ba2\u5355',
            },
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together=set([('source', 'recipe_num')]),
        ),
    ]
