# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-06 05:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='\u6807\u9898')),
                ('description', models.TextField(verbose_name='\u7b80\u8ff0')),
                ('url', models.URLField(verbose_name='\u6587\u7ae0\u94fe\u63a5')),
                ('article_type', models.CharField(choices=[('CYHW', '\u521b\u4e1a\u597d\u6587'), ('CYKT', '\u521b\u4e1a\u8bfe\u5802')], max_length=200, verbose_name='\u6587\u7ae0\u7c7b\u578b')),
                ('picture', models.ImageField(upload_to=b'', verbose_name='\u56fe\u7247')),
            ],
            options={
                'verbose_name': '\u6587\u7ae0',
                'verbose_name_plural': '\u82e5\u5e72\u6587\u7ae0',
            },
        ),
    ]
