# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-06 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20160306_0546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='picture',
            field=models.ImageField(upload_to='/Users/chaihaotian/Documents/workspace/django_skeleton/my_project/static%Y/%m/%d', verbose_name='\u56fe\u7247'),
        ),
    ]
