# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-08 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20160307_0626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='article_type',
            field=models.CharField(choices=[('CYHW', '\u521b\u4e1a\u597d\u6587'), ('CYKT', '\u521b\u4e1a\u8bfe\u5802'), ('TSGJ', '\u8c08\u53e4\u8bf4\u4eca')], max_length=200, verbose_name='\u6587\u7ae0\u7c7b\u578b'),
        ),
    ]
