# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-06 06:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='\u6807\u9898')),
                ('description', models.TextField(verbose_name='\u6d3b\u52a8\u8be6\u60c5')),
                ('picture', models.ImageField(upload_to='static/activity/%Y/%m/%d', verbose_name='\u6d3b\u52a8\u56fe\u7247')),
                ('url', models.URLField(verbose_name='\u6d3b\u52a8\u94fe\u63a5')),
                ('main_organizer', models.CharField(max_length=200, verbose_name='\u4e3b\u529e\u5355\u4f4d')),
                ('union_organizer', models.CharField(max_length=200, verbose_name='\u8054\u5408\u4e3b\u529e')),
                ('partner', models.CharField(max_length=200, verbose_name='\u5408\u4f5c\u4f19\u4f34')),
                ('activity_time', models.CharField(max_length=200, verbose_name='\u6d3b\u52a8\u65f6\u95f4')),
                ('location', models.CharField(max_length=200, verbose_name='\u6d3b\u52a8\u5730\u70b9')),
            ],
            options={
                'verbose_name': '\u6d3b\u52a8',
                'verbose_name_plural': '\u82e5\u5e72\u6d3b\u52a8',
            },
        ),
        migrations.CreateModel(
            name='ActivityFlow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('start_time', models.CharField(max_length=200, verbose_name='\u5f00\u59cb\u65f6\u95f4')),
                ('end_time', models.CharField(max_length=200, verbose_name='\u7ed3\u675f\u65f6\u95f4')),
                ('description', models.CharField(max_length=200, verbose_name='\u6d41\u7a0b\u8bf4\u660e')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.Activity')),
            ],
            options={
                'verbose_name': '\u6d41\u7a0b',
                'verbose_name_plural': '\u82e5\u5e72\u6d41\u7a0b',
            },
        ),
    ]
