# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-07 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name': '\u6d3b\u52a8', 'verbose_name_plural': '\u6d3b\u52a8'},
        ),
        migrations.AlterModelOptions(
            name='activityflow',
            options={'verbose_name': '\u6d41\u7a0b', 'verbose_name_plural': '\u6d41\u7a0b'},
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_time',
            field=models.DateTimeField(verbose_name='\u6d3b\u52a8\u65f6\u95f4'),
        ),
    ]
